'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace InsignaWs
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="verifyOperationWrapper", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class verifyOperationWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private originalChainField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private signTransactionIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property originalChain() As String
            Get
                Return Me.originalChainField
            End Get
            Set
                If (Object.ReferenceEquals(Me.originalChainField, value) <> true) Then
                    Me.originalChainField = value
                    Me.RaisePropertyChanged("originalChain")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property signTransactionId() As String
            Get
                Return Me.signTransactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.signTransactionIdField, value) <> true) Then
                    Me.signTransactionIdField = value
                    Me.RaisePropertyChanged("signTransactionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GenericResult", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(InsignaWs.CfdiValidateResult)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(InsignaWs.CfdiCancelResult)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(InsignaWs.CfdiInfoResult)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(InsignaWs.CfdiSignResult)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(InsignaWs.OperationVerifyResult))>  _
    Partial Public Class GenericResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private responseCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private responseDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private serverTransactionIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private requestDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private responseDateField As Date
        
        Private executionTimeField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property responseCode() As Integer
            Get
                Return Me.responseCodeField
            End Get
            Set
                If (Me.responseCodeField.Equals(value) <> true) Then
                    Me.responseCodeField = value
                    Me.RaisePropertyChanged("responseCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property responseDescription() As String
            Get
                Return Me.responseDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.responseDescriptionField, value) <> true) Then
                    Me.responseDescriptionField = value
                    Me.RaisePropertyChanged("responseDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property serverTransactionId() As String
            Get
                Return Me.serverTransactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.serverTransactionIdField, value) <> true) Then
                    Me.serverTransactionIdField = value
                    Me.RaisePropertyChanged("serverTransactionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property requestDate() As Date
            Get
                Return Me.requestDateField
            End Get
            Set
                If (Me.requestDateField.Equals(value) <> true) Then
                    Me.requestDateField = value
                    Me.RaisePropertyChanged("requestDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property responseDate() As Date
            Get
                Return Me.responseDateField
            End Get
            Set
                If (Me.responseDateField.Equals(value) <> true) Then
                    Me.responseDateField = value
                    Me.RaisePropertyChanged("responseDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property executionTime() As Long
            Get
                Return Me.executionTimeField
            End Get
            Set
                If (Me.executionTimeField.Equals(value) <> true) Then
                    Me.executionTimeField = value
                    Me.RaisePropertyChanged("executionTime")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CfdiValidateResult", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CfdiValidateResult
        Inherits InsignaWs.GenericResult
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CfdiCancelResult", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CfdiCancelResult
        Inherits InsignaWs.GenericResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private receiptField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property receipt() As String
            Get
                Return Me.receiptField
            End Get
            Set
                If (Object.ReferenceEquals(Me.receiptField, value) <> true) Then
                    Me.receiptField = value
                    Me.RaisePropertyChanged("receipt")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CfdiInfoResult", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CfdiInfoResult
        Inherits InsignaWs.GenericResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private uuidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cfdiStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cfdiField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.uuidField, value) <> true) Then
                    Me.uuidField = value
                    Me.RaisePropertyChanged("uuid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property cfdiStatus() As String
            Get
                Return Me.cfdiStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cfdiStatusField, value) <> true) Then
                    Me.cfdiStatusField = value
                    Me.RaisePropertyChanged("cfdiStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property cfdi() As String
            Get
                Return Me.cfdiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cfdiField, value) <> true) Then
                    Me.cfdiField = value
                    Me.RaisePropertyChanged("cfdi")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CfdiSignResult", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CfdiSignResult
        Inherits InsignaWs.GenericResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private signedXmlField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private uuidField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property signedXml() As String
            Get
                Return Me.signedXmlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.signedXmlField, value) <> true) Then
                    Me.signedXmlField = value
                    Me.RaisePropertyChanged("signedXml")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.uuidField, value) <> true) Then
                    Me.uuidField = value
                    Me.RaisePropertyChanged("uuid")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OperationVerifyResult", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OperationVerifyResult
        Inherits InsignaWs.GenericResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private uuidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cfdiStatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cfdiField As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.uuidField, value) <> true) Then
                    Me.uuidField = value
                    Me.RaisePropertyChanged("uuid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property cfdiStatus() As String
            Get
                Return Me.cfdiStatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cfdiStatusField, value) <> true) Then
                    Me.cfdiStatusField = value
                    Me.RaisePropertyChanged("cfdiStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property cfdi() As String
            Get
                Return Me.cfdiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cfdiField, value) <> true) Then
                    Me.cfdiField = value
                    Me.RaisePropertyChanged("cfdi")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="operationFailed", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class operationFailed
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private errorCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private errorDescriptionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private serverTransactionIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private requestDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private responseDateField As Date
        
        Private executionTimeField As Long
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property errorCode() As Integer
            Get
                Return Me.errorCodeField
            End Get
            Set
                If (Me.errorCodeField.Equals(value) <> true) Then
                    Me.errorCodeField = value
                    Me.RaisePropertyChanged("errorCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property errorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.errorDescriptionField, value) <> true) Then
                    Me.errorDescriptionField = value
                    Me.RaisePropertyChanged("errorDescription")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property serverTransactionId() As String
            Get
                Return Me.serverTransactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.serverTransactionIdField, value) <> true) Then
                    Me.serverTransactionIdField = value
                    Me.RaisePropertyChanged("serverTransactionId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property requestDate() As Date
            Get
                Return Me.requestDateField
            End Get
            Set
                If (Me.requestDateField.Equals(value) <> true) Then
                    Me.requestDateField = value
                    Me.RaisePropertyChanged("requestDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property responseDate() As Date
            Get
                Return Me.responseDateField
            End Get
            Set
                If (Me.responseDateField.Equals(value) <> true) Then
                    Me.responseDateField = value
                    Me.RaisePropertyChanged("responseDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property executionTime() As Long
            Get
                Return Me.executionTimeField
            End Get
            Set
                If (Me.executionTimeField.Equals(value) <> true) Then
                    Me.executionTimeField = value
                    Me.RaisePropertyChanged("executionTime")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="validateCfdiWrapper", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class validateCfdiWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private cfdiField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property cfdi() As String
            Get
                Return Me.cfdiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cfdiField, value) <> true) Then
                    Me.cfdiField = value
                    Me.RaisePropertyChanged("cfdi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cfdiCancelWrapper", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class cfdiCancelWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private uuidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private signatureValueField As String
        
        Private cancelationDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private certificateField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.uuidField, value) <> true) Then
                    Me.uuidField = value
                    Me.RaisePropertyChanged("uuid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property signatureValue() As String
            Get
                Return Me.signatureValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.signatureValueField, value) <> true) Then
                    Me.signatureValueField = value
                    Me.RaisePropertyChanged("signatureValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property cancelationDate() As Date
            Get
                Return Me.cancelationDateField
            End Get
            Set
                If (Me.cancelationDateField.Equals(value) <> true) Then
                    Me.cancelationDateField = value
                    Me.RaisePropertyChanged("cancelationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property certificate() As String
            Get
                Return Me.certificateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.certificateField, value) <> true) Then
                    Me.certificateField = value
                    Me.RaisePropertyChanged("certificate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cfdiInfoWrapper", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class cfdiInfoWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private uuidField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.uuidField, value) <> true) Then
                    Me.uuidField = value
                    Me.RaisePropertyChanged("uuid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="cfdiSignWrapper", [Namespace]:="http://ws.certipass.mx/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class cfdiSignWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private cfdiField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private transactionIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property cfdi() As String
            Get
                Return Me.cfdiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cfdiField, value) <> true) Then
                    Me.cfdiField = value
                    Me.RaisePropertyChanged("cfdi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property transactionId() As String
            Get
                Return Me.transactionIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.transactionIdField, value) <> true) Then
                    Me.transactionIdField = value
                    Me.RaisePropertyChanged("transactionId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.certipass.mx/", ConfigurationName:="InsignaWs.InsignaSOAPWS")>  _
    Public Interface InsignaSOAPWS
        
        'CODEGEN: Generating message contract since element name verifyOperationWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/verifyOperation", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/verifyOperationResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(InsignaWs.operationFailed), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="OperationFailed")>  _
        Function verifyOperation(ByVal request As InsignaWs.verifyOperation) As InsignaWs.verifyOperationResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/verifyOperation", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/verifyOperationResponse")>  _
        Function verifyOperationAsync(ByVal request As InsignaWs.verifyOperation) As System.Threading.Tasks.Task(Of InsignaWs.verifyOperationResponse)
        
        'CODEGEN: Generating message contract since element name validateCfdiWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/validateCfdi", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/validateCfdiResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(InsignaWs.operationFailed), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="OperationFailed")>  _
        Function validateCfdi(ByVal request As InsignaWs.validateCfdi) As InsignaWs.validateCfdiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/validateCfdi", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/validateCfdiResponse")>  _
        Function validateCfdiAsync(ByVal request As InsignaWs.validateCfdi) As System.Threading.Tasks.Task(Of InsignaWs.validateCfdiResponse)
        
        'CODEGEN: Generating message contract since element name cfdiCancelWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdi", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdiResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(InsignaWs.operationFailed), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="OperationFailed")>  _
        Function cancelCfdi(ByVal request As InsignaWs.cancelCfdi) As InsignaWs.cancelCfdiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdi", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdiResponse")>  _
        Function cancelCfdiAsync(ByVal request As InsignaWs.cancelCfdi) As System.Threading.Tasks.Task(Of InsignaWs.cancelCfdiResponse)
        
        'CODEGEN: Generating message contract since element name cfdiInfoWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfo", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfoResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(InsignaWs.operationFailed), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="OperationFailed")>  _
        Function getCfdiInfo(ByVal request As InsignaWs.getCfdiInfo) As InsignaWs.getCfdiInfoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfo", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfoResponse")>  _
        Function getCfdiInfoAsync(ByVal request As InsignaWs.getCfdiInfo) As System.Threading.Tasks.Task(Of InsignaWs.getCfdiInfoResponse)
        
        'CODEGEN: Generating message contract since element name cfdiSignWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/signCfdi", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/signCfdiResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(InsignaWs.operationFailed), Action:="http://www.w3.org/2005/08/addressing/soap/fault", Name:="OperationFailed")>  _
        Function signCfdi(ByVal request As InsignaWs.signCfdi) As InsignaWs.signCfdiResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.certipass.mx/InsignaSOAPWS/signCfdi", ReplyAction:="http://ws.certipass.mx/InsignaSOAPWS/signCfdiResponse")>  _
        Function signCfdiAsync(ByVal request As InsignaWs.signCfdi) As System.Threading.Tasks.Task(Of InsignaWs.signCfdiResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class verifyOperation
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="verifyOperation", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.verifyOperationBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.verifyOperationBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class verifyOperationBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public verifyOperationWrapper As InsignaWs.verifyOperationWrapper
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal verifyOperationWrapper As InsignaWs.verifyOperationWrapper)
            MyBase.New
            Me.verifyOperationWrapper = verifyOperationWrapper
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class verifyOperationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="verifyOperationResponse", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.verifyOperationResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.verifyOperationResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class verifyOperationResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As InsignaWs.OperationVerifyResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As InsignaWs.OperationVerifyResult)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class validateCfdi
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="validateCfdi", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.validateCfdiBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.validateCfdiBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class validateCfdiBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public validateCfdiWrapper As InsignaWs.validateCfdiWrapper
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal validateCfdiWrapper As InsignaWs.validateCfdiWrapper)
            MyBase.New
            Me.validateCfdiWrapper = validateCfdiWrapper
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class validateCfdiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="validateCfdiResponse", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.validateCfdiResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.validateCfdiResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class validateCfdiResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As InsignaWs.CfdiValidateResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As InsignaWs.CfdiValidateResult)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class cancelCfdi
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="cancelCfdi", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.cancelCfdiBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.cancelCfdiBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class cancelCfdiBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cfdiCancelWrapper As InsignaWs.cfdiCancelWrapper
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cfdiCancelWrapper As InsignaWs.cfdiCancelWrapper)
            MyBase.New
            Me.cfdiCancelWrapper = cfdiCancelWrapper
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class cancelCfdiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="cancelCfdiResponse", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.cancelCfdiResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.cancelCfdiResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class cancelCfdiResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As InsignaWs.CfdiCancelResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As InsignaWs.CfdiCancelResult)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getCfdiInfo
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getCfdiInfo", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.getCfdiInfoBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.getCfdiInfoBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class getCfdiInfoBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cfdiInfoWrapper As InsignaWs.cfdiInfoWrapper
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cfdiInfoWrapper As InsignaWs.cfdiInfoWrapper)
            MyBase.New
            Me.cfdiInfoWrapper = cfdiInfoWrapper
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getCfdiInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getCfdiInfoResponse", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.getCfdiInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.getCfdiInfoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class getCfdiInfoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As InsignaWs.CfdiInfoResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As InsignaWs.CfdiInfoResult)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class signCfdi
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="signCfdi", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.signCfdiBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.signCfdiBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class signCfdiBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public cfdiSignWrapper As InsignaWs.cfdiSignWrapper
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cfdiSignWrapper As InsignaWs.cfdiSignWrapper)
            MyBase.New
            Me.cfdiSignWrapper = cfdiSignWrapper
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class signCfdiResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="signCfdiResponse", [Namespace]:="http://ws.certipass.mx/", Order:=0)>  _
        Public Body As InsignaWs.signCfdiResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As InsignaWs.signCfdiResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://ws.certipass.mx/")>  _
    Partial Public Class signCfdiResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public [return] As InsignaWs.CfdiSignResult
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As InsignaWs.CfdiSignResult)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InsignaSOAPWSChannel
        Inherits InsignaWs.InsignaSOAPWS, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InsignaSOAPWSClient
        Inherits System.ServiceModel.ClientBase(Of InsignaWs.InsignaSOAPWS)
        Implements InsignaWs.InsignaSOAPWS
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_verifyOperation(ByVal request As InsignaWs.verifyOperation) As InsignaWs.verifyOperationResponse Implements InsignaWs.InsignaSOAPWS.verifyOperation
            Return MyBase.Channel.verifyOperation(request)
        End Function
        
        Public Function verifyOperation(ByVal verifyOperationWrapper As InsignaWs.verifyOperationWrapper) As InsignaWs.OperationVerifyResult
            Dim inValue As InsignaWs.verifyOperation = New InsignaWs.verifyOperation()
            inValue.Body = New InsignaWs.verifyOperationBody()
            inValue.Body.verifyOperationWrapper = verifyOperationWrapper
            Dim retVal As InsignaWs.verifyOperationResponse = CType(Me,InsignaWs.InsignaSOAPWS).verifyOperation(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_verifyOperationAsync(ByVal request As InsignaWs.verifyOperation) As System.Threading.Tasks.Task(Of InsignaWs.verifyOperationResponse) Implements InsignaWs.InsignaSOAPWS.verifyOperationAsync
            Return MyBase.Channel.verifyOperationAsync(request)
        End Function
        
        Public Function verifyOperationAsync(ByVal verifyOperationWrapper As InsignaWs.verifyOperationWrapper) As System.Threading.Tasks.Task(Of InsignaWs.verifyOperationResponse)
            Dim inValue As InsignaWs.verifyOperation = New InsignaWs.verifyOperation()
            inValue.Body = New InsignaWs.verifyOperationBody()
            inValue.Body.verifyOperationWrapper = verifyOperationWrapper
            Return CType(Me,InsignaWs.InsignaSOAPWS).verifyOperationAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_validateCfdi(ByVal request As InsignaWs.validateCfdi) As InsignaWs.validateCfdiResponse Implements InsignaWs.InsignaSOAPWS.validateCfdi
            Return MyBase.Channel.validateCfdi(request)
        End Function
        
        Public Function validateCfdi(ByVal validateCfdiWrapper As InsignaWs.validateCfdiWrapper) As InsignaWs.CfdiValidateResult
            Dim inValue As InsignaWs.validateCfdi = New InsignaWs.validateCfdi()
            inValue.Body = New InsignaWs.validateCfdiBody()
            inValue.Body.validateCfdiWrapper = validateCfdiWrapper
            Dim retVal As InsignaWs.validateCfdiResponse = CType(Me,InsignaWs.InsignaSOAPWS).validateCfdi(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_validateCfdiAsync(ByVal request As InsignaWs.validateCfdi) As System.Threading.Tasks.Task(Of InsignaWs.validateCfdiResponse) Implements InsignaWs.InsignaSOAPWS.validateCfdiAsync
            Return MyBase.Channel.validateCfdiAsync(request)
        End Function
        
        Public Function validateCfdiAsync(ByVal validateCfdiWrapper As InsignaWs.validateCfdiWrapper) As System.Threading.Tasks.Task(Of InsignaWs.validateCfdiResponse)
            Dim inValue As InsignaWs.validateCfdi = New InsignaWs.validateCfdi()
            inValue.Body = New InsignaWs.validateCfdiBody()
            inValue.Body.validateCfdiWrapper = validateCfdiWrapper
            Return CType(Me,InsignaWs.InsignaSOAPWS).validateCfdiAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_cancelCfdi(ByVal request As InsignaWs.cancelCfdi) As InsignaWs.cancelCfdiResponse Implements InsignaWs.InsignaSOAPWS.cancelCfdi
            Return MyBase.Channel.cancelCfdi(request)
        End Function
        
        Public Function cancelCfdi(ByVal cfdiCancelWrapper As InsignaWs.cfdiCancelWrapper) As InsignaWs.CfdiCancelResult
            Dim inValue As InsignaWs.cancelCfdi = New InsignaWs.cancelCfdi()
            inValue.Body = New InsignaWs.cancelCfdiBody()
            inValue.Body.cfdiCancelWrapper = cfdiCancelWrapper
            Dim retVal As InsignaWs.cancelCfdiResponse = CType(Me,InsignaWs.InsignaSOAPWS).cancelCfdi(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_cancelCfdiAsync(ByVal request As InsignaWs.cancelCfdi) As System.Threading.Tasks.Task(Of InsignaWs.cancelCfdiResponse) Implements InsignaWs.InsignaSOAPWS.cancelCfdiAsync
            Return MyBase.Channel.cancelCfdiAsync(request)
        End Function
        
        Public Function cancelCfdiAsync(ByVal cfdiCancelWrapper As InsignaWs.cfdiCancelWrapper) As System.Threading.Tasks.Task(Of InsignaWs.cancelCfdiResponse)
            Dim inValue As InsignaWs.cancelCfdi = New InsignaWs.cancelCfdi()
            inValue.Body = New InsignaWs.cancelCfdiBody()
            inValue.Body.cfdiCancelWrapper = cfdiCancelWrapper
            Return CType(Me,InsignaWs.InsignaSOAPWS).cancelCfdiAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_getCfdiInfo(ByVal request As InsignaWs.getCfdiInfo) As InsignaWs.getCfdiInfoResponse Implements InsignaWs.InsignaSOAPWS.getCfdiInfo
            Return MyBase.Channel.getCfdiInfo(request)
        End Function
        
        Public Function getCfdiInfo(ByVal cfdiInfoWrapper As InsignaWs.cfdiInfoWrapper) As InsignaWs.CfdiInfoResult
            Dim inValue As InsignaWs.getCfdiInfo = New InsignaWs.getCfdiInfo()
            inValue.Body = New InsignaWs.getCfdiInfoBody()
            inValue.Body.cfdiInfoWrapper = cfdiInfoWrapper
            Dim retVal As InsignaWs.getCfdiInfoResponse = CType(Me,InsignaWs.InsignaSOAPWS).getCfdiInfo(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_getCfdiInfoAsync(ByVal request As InsignaWs.getCfdiInfo) As System.Threading.Tasks.Task(Of InsignaWs.getCfdiInfoResponse) Implements InsignaWs.InsignaSOAPWS.getCfdiInfoAsync
            Return MyBase.Channel.getCfdiInfoAsync(request)
        End Function
        
        Public Function getCfdiInfoAsync(ByVal cfdiInfoWrapper As InsignaWs.cfdiInfoWrapper) As System.Threading.Tasks.Task(Of InsignaWs.getCfdiInfoResponse)
            Dim inValue As InsignaWs.getCfdiInfo = New InsignaWs.getCfdiInfo()
            inValue.Body = New InsignaWs.getCfdiInfoBody()
            inValue.Body.cfdiInfoWrapper = cfdiInfoWrapper
            Return CType(Me,InsignaWs.InsignaSOAPWS).getCfdiInfoAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_signCfdi(ByVal request As InsignaWs.signCfdi) As InsignaWs.signCfdiResponse Implements InsignaWs.InsignaSOAPWS.signCfdi
            Return MyBase.Channel.signCfdi(request)
        End Function
        
        Public Function signCfdi(ByVal cfdiSignWrapper As InsignaWs.cfdiSignWrapper) As InsignaWs.CfdiSignResult
            Dim inValue As InsignaWs.signCfdi = New InsignaWs.signCfdi()
            inValue.Body = New InsignaWs.signCfdiBody()
            inValue.Body.cfdiSignWrapper = cfdiSignWrapper
            Dim retVal As InsignaWs.signCfdiResponse = CType(Me,InsignaWs.InsignaSOAPWS).signCfdi(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function InsignaWs_InsignaSOAPWS_signCfdiAsync(ByVal request As InsignaWs.signCfdi) As System.Threading.Tasks.Task(Of InsignaWs.signCfdiResponse) Implements InsignaWs.InsignaSOAPWS.signCfdiAsync
            Return MyBase.Channel.signCfdiAsync(request)
        End Function
        
        Public Function signCfdiAsync(ByVal cfdiSignWrapper As InsignaWs.cfdiSignWrapper) As System.Threading.Tasks.Task(Of InsignaWs.signCfdiResponse)
            Dim inValue As InsignaWs.signCfdi = New InsignaWs.signCfdi()
            inValue.Body = New InsignaWs.signCfdiBody()
            inValue.Body.cfdiSignWrapper = cfdiSignWrapper
            Return CType(Me,InsignaWs.InsignaSOAPWS).signCfdiAsync(inValue)
        End Function
    End Class
End Namespace
