//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsignaWsClient.InsignaWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="verifyOperationWrapper", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class verifyOperationWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string originalChainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string originalChain {
            get {
                return this.originalChainField;
            }
            set {
                if ((object.ReferenceEquals(this.originalChainField, value) != true)) {
                    this.originalChainField = value;
                    this.RaisePropertyChanged("originalChain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string signTransactionId {
            get {
                return this.signTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.signTransactionIdField, value) != true)) {
                    this.signTransactionIdField = value;
                    this.RaisePropertyChanged("signTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericResult", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InsignaWsClient.InsignaWs.CfdiValidateResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InsignaWsClient.InsignaWs.CfdiCancelResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InsignaWsClient.InsignaWs.CfdiInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InsignaWsClient.InsignaWs.CfdiSignResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InsignaWsClient.InsignaWs.OperationVerifyResult))]
    public partial class GenericResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int responseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serverTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime responseDateField;
        
        private long executionTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                if ((this.responseCodeField.Equals(value) != true)) {
                    this.responseCodeField = value;
                    this.RaisePropertyChanged("responseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.responseDescriptionField, value) != true)) {
                    this.responseDescriptionField = value;
                    this.RaisePropertyChanged("responseDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serverTransactionId {
            get {
                return this.serverTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.serverTransactionIdField, value) != true)) {
                    this.serverTransactionIdField = value;
                    this.RaisePropertyChanged("serverTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime responseDate {
            get {
                return this.responseDateField;
            }
            set {
                if ((this.responseDateField.Equals(value) != true)) {
                    this.responseDateField = value;
                    this.RaisePropertyChanged("responseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long executionTime {
            get {
                return this.executionTimeField;
            }
            set {
                if ((this.executionTimeField.Equals(value) != true)) {
                    this.executionTimeField = value;
                    this.RaisePropertyChanged("executionTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CfdiValidateResult", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class CfdiValidateResult : InsignaWsClient.InsignaWs.GenericResult {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CfdiCancelResult", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class CfdiCancelResult : InsignaWsClient.InsignaWs.GenericResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiptField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string receipt {
            get {
                return this.receiptField;
            }
            set {
                if ((object.ReferenceEquals(this.receiptField, value) != true)) {
                    this.receiptField = value;
                    this.RaisePropertyChanged("receipt");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CfdiInfoResult", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class CfdiInfoResult : InsignaWsClient.InsignaWs.GenericResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cfdiStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cfdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidField, value) != true)) {
                    this.uuidField = value;
                    this.RaisePropertyChanged("uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cfdiStatus {
            get {
                return this.cfdiStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.cfdiStatusField, value) != true)) {
                    this.cfdiStatusField = value;
                    this.RaisePropertyChanged("cfdiStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                if ((object.ReferenceEquals(this.cfdiField, value) != true)) {
                    this.cfdiField = value;
                    this.RaisePropertyChanged("cfdi");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CfdiSignResult", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class CfdiSignResult : InsignaWsClient.InsignaWs.GenericResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signedXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string signedXml {
            get {
                return this.signedXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.signedXmlField, value) != true)) {
                    this.signedXmlField = value;
                    this.RaisePropertyChanged("signedXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidField, value) != true)) {
                    this.uuidField = value;
                    this.RaisePropertyChanged("uuid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationVerifyResult", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class OperationVerifyResult : InsignaWsClient.InsignaWs.GenericResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cfdiStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cfdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidField, value) != true)) {
                    this.uuidField = value;
                    this.RaisePropertyChanged("uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cfdiStatus {
            get {
                return this.cfdiStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.cfdiStatusField, value) != true)) {
                    this.cfdiStatusField = value;
                    this.RaisePropertyChanged("cfdiStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                if ((object.ReferenceEquals(this.cfdiField, value) != true)) {
                    this.cfdiField = value;
                    this.RaisePropertyChanged("cfdi");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="operationFailed", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class operationFailed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serverTransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime responseDateField;
        
        private long executionTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((this.errorCodeField.Equals(value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.errorDescriptionField, value) != true)) {
                    this.errorDescriptionField = value;
                    this.RaisePropertyChanged("errorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string serverTransactionId {
            get {
                return this.serverTransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.serverTransactionIdField, value) != true)) {
                    this.serverTransactionIdField = value;
                    this.RaisePropertyChanged("serverTransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime responseDate {
            get {
                return this.responseDateField;
            }
            set {
                if ((this.responseDateField.Equals(value) != true)) {
                    this.responseDateField = value;
                    this.RaisePropertyChanged("responseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long executionTime {
            get {
                return this.executionTimeField;
            }
            set {
                if ((this.executionTimeField.Equals(value) != true)) {
                    this.executionTimeField = value;
                    this.RaisePropertyChanged("executionTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="validateCfdiWrapper", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class validateCfdiWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cfdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                if ((object.ReferenceEquals(this.cfdiField, value) != true)) {
                    this.cfdiField = value;
                    this.RaisePropertyChanged("cfdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cfdiCancelWrapper", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class cfdiCancelWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signatureValueField;
        
        private System.DateTime cancelationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string certificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidField, value) != true)) {
                    this.uuidField = value;
                    this.RaisePropertyChanged("uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string signatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                if ((object.ReferenceEquals(this.signatureValueField, value) != true)) {
                    this.signatureValueField = value;
                    this.RaisePropertyChanged("signatureValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime cancelationDate {
            get {
                return this.cancelationDateField;
            }
            set {
                if ((this.cancelationDateField.Equals(value) != true)) {
                    this.cancelationDateField = value;
                    this.RaisePropertyChanged("cancelationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string certificate {
            get {
                return this.certificateField;
            }
            set {
                if ((object.ReferenceEquals(this.certificateField, value) != true)) {
                    this.certificateField = value;
                    this.RaisePropertyChanged("certificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cfdiInfoWrapper", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class cfdiInfoWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.uuidField, value) != true)) {
                    this.uuidField = value;
                    this.RaisePropertyChanged("uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cfdiSignWrapper", Namespace="http://ws.certipass.mx/")]
    [System.SerializableAttribute()]
    public partial class cfdiSignWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cfdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string cfdi {
            get {
                return this.cfdiField;
            }
            set {
                if ((object.ReferenceEquals(this.cfdiField, value) != true)) {
                    this.cfdiField = value;
                    this.RaisePropertyChanged("cfdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionIdField, value) != true)) {
                    this.transactionIdField = value;
                    this.RaisePropertyChanged("transactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.certipass.mx/", ConfigurationName="InsignaWs.InsignaSOAPWS")]
    public interface InsignaSOAPWS {
        
        // CODEGEN: Generating message contract since element name verifyOperationWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/verifyOperation", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/verifyOperationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsignaWsClient.InsignaWs.operationFailed), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="OperationFailed")]
        InsignaWsClient.InsignaWs.verifyOperationResponse verifyOperation(InsignaWsClient.InsignaWs.verifyOperation request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/verifyOperation", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/verifyOperationResponse")]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.verifyOperationResponse> verifyOperationAsync(InsignaWsClient.InsignaWs.verifyOperation request);
        
        // CODEGEN: Generating message contract since element name validateCfdiWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/validateCfdi", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/validateCfdiResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsignaWsClient.InsignaWs.operationFailed), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="OperationFailed")]
        InsignaWsClient.InsignaWs.validateCfdiResponse validateCfdi(InsignaWsClient.InsignaWs.validateCfdi request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/validateCfdi", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/validateCfdiResponse")]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.validateCfdiResponse> validateCfdiAsync(InsignaWsClient.InsignaWs.validateCfdi request);
        
        // CODEGEN: Generating message contract since element name cfdiCancelWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdi", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdiResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsignaWsClient.InsignaWs.operationFailed), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="OperationFailed")]
        InsignaWsClient.InsignaWs.cancelCfdiResponse cancelCfdi(InsignaWsClient.InsignaWs.cancelCfdi request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdi", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/cancelCfdiResponse")]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.cancelCfdiResponse> cancelCfdiAsync(InsignaWsClient.InsignaWs.cancelCfdi request);
        
        // CODEGEN: Generating message contract since element name cfdiInfoWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfo", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsignaWsClient.InsignaWs.operationFailed), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="OperationFailed")]
        InsignaWsClient.InsignaWs.getCfdiInfoResponse getCfdiInfo(InsignaWsClient.InsignaWs.getCfdiInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfo", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/getCfdiInfoResponse")]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.getCfdiInfoResponse> getCfdiInfoAsync(InsignaWsClient.InsignaWs.getCfdiInfo request);
        
        // CODEGEN: Generating message contract since element name cfdiSignWrapper from namespace http://ws.certipass.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/signCfdi", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/signCfdiResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(InsignaWsClient.InsignaWs.operationFailed), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="OperationFailed")]
        InsignaWsClient.InsignaWs.signCfdiResponse signCfdi(InsignaWsClient.InsignaWs.signCfdi request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.certipass.mx/InsignaSOAPWS/signCfdi", ReplyAction="http://ws.certipass.mx/InsignaSOAPWS/signCfdiResponse")]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.signCfdiResponse> signCfdiAsync(InsignaWsClient.InsignaWs.signCfdi request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyOperation {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyOperation", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.verifyOperationBody Body;
        
        public verifyOperation() {
        }
        
        public verifyOperation(InsignaWsClient.InsignaWs.verifyOperationBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class verifyOperationBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.verifyOperationWrapper verifyOperationWrapper;
        
        public verifyOperationBody() {
        }
        
        public verifyOperationBody(InsignaWsClient.InsignaWs.verifyOperationWrapper verifyOperationWrapper) {
            this.verifyOperationWrapper = verifyOperationWrapper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verifyOperationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verifyOperationResponse", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.verifyOperationResponseBody Body;
        
        public verifyOperationResponse() {
        }
        
        public verifyOperationResponse(InsignaWsClient.InsignaWs.verifyOperationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class verifyOperationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.OperationVerifyResult @return;
        
        public verifyOperationResponseBody() {
        }
        
        public verifyOperationResponseBody(InsignaWsClient.InsignaWs.OperationVerifyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateCfdi {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateCfdi", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.validateCfdiBody Body;
        
        public validateCfdi() {
        }
        
        public validateCfdi(InsignaWsClient.InsignaWs.validateCfdiBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class validateCfdiBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.validateCfdiWrapper validateCfdiWrapper;
        
        public validateCfdiBody() {
        }
        
        public validateCfdiBody(InsignaWsClient.InsignaWs.validateCfdiWrapper validateCfdiWrapper) {
            this.validateCfdiWrapper = validateCfdiWrapper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validateCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validateCfdiResponse", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.validateCfdiResponseBody Body;
        
        public validateCfdiResponse() {
        }
        
        public validateCfdiResponse(InsignaWsClient.InsignaWs.validateCfdiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class validateCfdiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.CfdiValidateResult @return;
        
        public validateCfdiResponseBody() {
        }
        
        public validateCfdiResponseBody(InsignaWsClient.InsignaWs.CfdiValidateResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelCfdi {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelCfdi", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.cancelCfdiBody Body;
        
        public cancelCfdi() {
        }
        
        public cancelCfdi(InsignaWsClient.InsignaWs.cancelCfdiBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class cancelCfdiBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.cfdiCancelWrapper cfdiCancelWrapper;
        
        public cancelCfdiBody() {
        }
        
        public cancelCfdiBody(InsignaWsClient.InsignaWs.cfdiCancelWrapper cfdiCancelWrapper) {
            this.cfdiCancelWrapper = cfdiCancelWrapper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cancelCfdiResponse", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.cancelCfdiResponseBody Body;
        
        public cancelCfdiResponse() {
        }
        
        public cancelCfdiResponse(InsignaWsClient.InsignaWs.cancelCfdiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class cancelCfdiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.CfdiCancelResult @return;
        
        public cancelCfdiResponseBody() {
        }
        
        public cancelCfdiResponseBody(InsignaWsClient.InsignaWs.CfdiCancelResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCfdiInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCfdiInfo", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.getCfdiInfoBody Body;
        
        public getCfdiInfo() {
        }
        
        public getCfdiInfo(InsignaWsClient.InsignaWs.getCfdiInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class getCfdiInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.cfdiInfoWrapper cfdiInfoWrapper;
        
        public getCfdiInfoBody() {
        }
        
        public getCfdiInfoBody(InsignaWsClient.InsignaWs.cfdiInfoWrapper cfdiInfoWrapper) {
            this.cfdiInfoWrapper = cfdiInfoWrapper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCfdiInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCfdiInfoResponse", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.getCfdiInfoResponseBody Body;
        
        public getCfdiInfoResponse() {
        }
        
        public getCfdiInfoResponse(InsignaWsClient.InsignaWs.getCfdiInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class getCfdiInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.CfdiInfoResult @return;
        
        public getCfdiInfoResponseBody() {
        }
        
        public getCfdiInfoResponseBody(InsignaWsClient.InsignaWs.CfdiInfoResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signCfdi {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signCfdi", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.signCfdiBody Body;
        
        public signCfdi() {
        }
        
        public signCfdi(InsignaWsClient.InsignaWs.signCfdiBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class signCfdiBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.cfdiSignWrapper cfdiSignWrapper;
        
        public signCfdiBody() {
        }
        
        public signCfdiBody(InsignaWsClient.InsignaWs.cfdiSignWrapper cfdiSignWrapper) {
            this.cfdiSignWrapper = cfdiSignWrapper;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signCfdiResponse", Namespace="http://ws.certipass.mx/", Order=0)]
        public InsignaWsClient.InsignaWs.signCfdiResponseBody Body;
        
        public signCfdiResponse() {
        }
        
        public signCfdiResponse(InsignaWsClient.InsignaWs.signCfdiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.certipass.mx/")]
    public partial class signCfdiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public InsignaWsClient.InsignaWs.CfdiSignResult @return;
        
        public signCfdiResponseBody() {
        }
        
        public signCfdiResponseBody(InsignaWsClient.InsignaWs.CfdiSignResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InsignaSOAPWSChannel : InsignaWsClient.InsignaWs.InsignaSOAPWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsignaSOAPWSClient : System.ServiceModel.ClientBase<InsignaWsClient.InsignaWs.InsignaSOAPWS>, InsignaWsClient.InsignaWs.InsignaSOAPWS {
        
        public InsignaSOAPWSClient() {
        }
        
        public InsignaSOAPWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsignaSOAPWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsignaSOAPWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsignaSOAPWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsignaWsClient.InsignaWs.verifyOperationResponse InsignaWsClient.InsignaWs.InsignaSOAPWS.verifyOperation(InsignaWsClient.InsignaWs.verifyOperation request) {
            return base.Channel.verifyOperation(request);
        }
        
        public InsignaWsClient.InsignaWs.OperationVerifyResult verifyOperation(InsignaWsClient.InsignaWs.verifyOperationWrapper verifyOperationWrapper) {
            InsignaWsClient.InsignaWs.verifyOperation inValue = new InsignaWsClient.InsignaWs.verifyOperation();
            inValue.Body = new InsignaWsClient.InsignaWs.verifyOperationBody();
            inValue.Body.verifyOperationWrapper = verifyOperationWrapper;
            InsignaWsClient.InsignaWs.verifyOperationResponse retVal = ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).verifyOperation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.verifyOperationResponse> InsignaWsClient.InsignaWs.InsignaSOAPWS.verifyOperationAsync(InsignaWsClient.InsignaWs.verifyOperation request) {
            return base.Channel.verifyOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.verifyOperationResponse> verifyOperationAsync(InsignaWsClient.InsignaWs.verifyOperationWrapper verifyOperationWrapper) {
            InsignaWsClient.InsignaWs.verifyOperation inValue = new InsignaWsClient.InsignaWs.verifyOperation();
            inValue.Body = new InsignaWsClient.InsignaWs.verifyOperationBody();
            inValue.Body.verifyOperationWrapper = verifyOperationWrapper;
            return ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).verifyOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsignaWsClient.InsignaWs.validateCfdiResponse InsignaWsClient.InsignaWs.InsignaSOAPWS.validateCfdi(InsignaWsClient.InsignaWs.validateCfdi request) {
            return base.Channel.validateCfdi(request);
        }
        
        public InsignaWsClient.InsignaWs.CfdiValidateResult validateCfdi(InsignaWsClient.InsignaWs.validateCfdiWrapper validateCfdiWrapper) {
            InsignaWsClient.InsignaWs.validateCfdi inValue = new InsignaWsClient.InsignaWs.validateCfdi();
            inValue.Body = new InsignaWsClient.InsignaWs.validateCfdiBody();
            inValue.Body.validateCfdiWrapper = validateCfdiWrapper;
            InsignaWsClient.InsignaWs.validateCfdiResponse retVal = ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).validateCfdi(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.validateCfdiResponse> InsignaWsClient.InsignaWs.InsignaSOAPWS.validateCfdiAsync(InsignaWsClient.InsignaWs.validateCfdi request) {
            return base.Channel.validateCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.validateCfdiResponse> validateCfdiAsync(InsignaWsClient.InsignaWs.validateCfdiWrapper validateCfdiWrapper) {
            InsignaWsClient.InsignaWs.validateCfdi inValue = new InsignaWsClient.InsignaWs.validateCfdi();
            inValue.Body = new InsignaWsClient.InsignaWs.validateCfdiBody();
            inValue.Body.validateCfdiWrapper = validateCfdiWrapper;
            return ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).validateCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsignaWsClient.InsignaWs.cancelCfdiResponse InsignaWsClient.InsignaWs.InsignaSOAPWS.cancelCfdi(InsignaWsClient.InsignaWs.cancelCfdi request) {
            return base.Channel.cancelCfdi(request);
        }
        
        public InsignaWsClient.InsignaWs.CfdiCancelResult cancelCfdi(InsignaWsClient.InsignaWs.cfdiCancelWrapper cfdiCancelWrapper) {
            InsignaWsClient.InsignaWs.cancelCfdi inValue = new InsignaWsClient.InsignaWs.cancelCfdi();
            inValue.Body = new InsignaWsClient.InsignaWs.cancelCfdiBody();
            inValue.Body.cfdiCancelWrapper = cfdiCancelWrapper;
            InsignaWsClient.InsignaWs.cancelCfdiResponse retVal = ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).cancelCfdi(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.cancelCfdiResponse> InsignaWsClient.InsignaWs.InsignaSOAPWS.cancelCfdiAsync(InsignaWsClient.InsignaWs.cancelCfdi request) {
            return base.Channel.cancelCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.cancelCfdiResponse> cancelCfdiAsync(InsignaWsClient.InsignaWs.cfdiCancelWrapper cfdiCancelWrapper) {
            InsignaWsClient.InsignaWs.cancelCfdi inValue = new InsignaWsClient.InsignaWs.cancelCfdi();
            inValue.Body = new InsignaWsClient.InsignaWs.cancelCfdiBody();
            inValue.Body.cfdiCancelWrapper = cfdiCancelWrapper;
            return ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).cancelCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsignaWsClient.InsignaWs.getCfdiInfoResponse InsignaWsClient.InsignaWs.InsignaSOAPWS.getCfdiInfo(InsignaWsClient.InsignaWs.getCfdiInfo request) {
            return base.Channel.getCfdiInfo(request);
        }
        
        public InsignaWsClient.InsignaWs.CfdiInfoResult getCfdiInfo(InsignaWsClient.InsignaWs.cfdiInfoWrapper cfdiInfoWrapper) {
            InsignaWsClient.InsignaWs.getCfdiInfo inValue = new InsignaWsClient.InsignaWs.getCfdiInfo();
            inValue.Body = new InsignaWsClient.InsignaWs.getCfdiInfoBody();
            inValue.Body.cfdiInfoWrapper = cfdiInfoWrapper;
            InsignaWsClient.InsignaWs.getCfdiInfoResponse retVal = ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).getCfdiInfo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.getCfdiInfoResponse> InsignaWsClient.InsignaWs.InsignaSOAPWS.getCfdiInfoAsync(InsignaWsClient.InsignaWs.getCfdiInfo request) {
            return base.Channel.getCfdiInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.getCfdiInfoResponse> getCfdiInfoAsync(InsignaWsClient.InsignaWs.cfdiInfoWrapper cfdiInfoWrapper) {
            InsignaWsClient.InsignaWs.getCfdiInfo inValue = new InsignaWsClient.InsignaWs.getCfdiInfo();
            inValue.Body = new InsignaWsClient.InsignaWs.getCfdiInfoBody();
            inValue.Body.cfdiInfoWrapper = cfdiInfoWrapper;
            return ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).getCfdiInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InsignaWsClient.InsignaWs.signCfdiResponse InsignaWsClient.InsignaWs.InsignaSOAPWS.signCfdi(InsignaWsClient.InsignaWs.signCfdi request) {
            return base.Channel.signCfdi(request);
        }
        
        public InsignaWsClient.InsignaWs.CfdiSignResult signCfdi(InsignaWsClient.InsignaWs.cfdiSignWrapper cfdiSignWrapper) {
            InsignaWsClient.InsignaWs.signCfdi inValue = new InsignaWsClient.InsignaWs.signCfdi();
            inValue.Body = new InsignaWsClient.InsignaWs.signCfdiBody();
            inValue.Body.cfdiSignWrapper = cfdiSignWrapper;
            InsignaWsClient.InsignaWs.signCfdiResponse retVal = ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).signCfdi(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.signCfdiResponse> InsignaWsClient.InsignaWs.InsignaSOAPWS.signCfdiAsync(InsignaWsClient.InsignaWs.signCfdi request) {
            return base.Channel.signCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<InsignaWsClient.InsignaWs.signCfdiResponse> signCfdiAsync(InsignaWsClient.InsignaWs.cfdiSignWrapper cfdiSignWrapper) {
            InsignaWsClient.InsignaWs.signCfdi inValue = new InsignaWsClient.InsignaWs.signCfdi();
            inValue.Body = new InsignaWsClient.InsignaWs.signCfdiBody();
            inValue.Body.cfdiSignWrapper = cfdiSignWrapper;
            return ((InsignaWsClient.InsignaWs.InsignaSOAPWS)(this)).signCfdiAsync(inValue);
        }
    }
}
